from abc import ABC, abstractmethod
from typing import AsyncGenerator, List, Dict, Any, Optional

class BaseLLM(ABC):
    """
    Abstract Base Interface for LLM Brain Adapters.
    """
    def __init__(self, model: str, temperature: float = 0.3, max_tokens: int = 150):
        self.model = model
        self.temperature = temperature
        self.max_tokens = max_tokens

    @abstractmethod
    async def generate_stream(
        self,
        messages: List[Dict[str, str]],
        system_prompt: str,
        tools: Optional[List[Dict[str, Any]]] = None
    ) -> AsyncGenerator[str, None]:
        """
        Yields text tokens as they are generated by the LLM (Sub-second streaming).
        """
        pass

    @abstractmethod
    async def generate(
        self,
        messages: List[Dict[str, str]],
        system_prompt: str
    ) -> str:
        """
        Non-streaming generation for summarization or batch processing.
        """
        pass
